### PR TITLE
Minor documentation updates

### PR DESCRIPTION
**Pull request by jarvist**
- linked to dev documentation on github pages
- update installation instructions in README, from dev documentation (package not registered yet)
- added reference to ArXiv paper in README and documentation
- Took a few sentences description from Abstract of ArXiv paper for README

Hopefully will make it easier for others to get started!

### CODE REVIEW

**Comment by jameskermode** [comment]
HI Jarvist

Thanks for the PR, but please note that this is not the version of the code used for the fully equivarient Hamiltonian fits described in our arXiv pre-print: this repo uses a Slater-Koster paramerterisation instead, which we found to be insufficiently accurate. 

The rewritten package is currently being cleaned up in a private repo and will be made public shortly, at which point we'll archive this repository,

This means I'll have to close your PR, but watch this space for the new version.

James

**Comment by jarvist** [comment]
Ah, maybe renaming this package ACEsktb.jl might help with the namespace confusion?

**Comment by jameskermode** [comment]
Good idea, will do.

**Comment by jarvist** [comment]
Hi James,

Are you any closer to releasing the 'full fat' ACE version?
A student Lucius Lu has now started with me, and ML TB will be his main
project.

Best wishes,

Jarv

**Comment by jameskermode** [comment]
We are certainly closer but not quite there yet. We hope to make the code public in the next 1-2 months.

**Comment by jarvist** [comment]
Thanks James! That's very useful to know.

**Pull request closed without merging**
